language: c
dist: trusty
sudo: false
group: beta

# To cache doc-building dependencies.
cache: pip

os:
  - linux
  # macOS builds are disabled as the machines are under-provisioned on Travis,
  # adding up to an extra hour completing a full CI run.
  #- osx

compiler:
  - clang
  - gcc

env:
  - TESTING=cpython

matrix:
  allow_failures:
    - env:
       - TESTING=coverage
  include:
    - os: linux
      language: python
      python: 3.5
      env:
        - TESTING=docs
      before_script:
        - cd Doc
        - make venv PYTHON=python3
      script:
        - make html SPHINXBUILD="./venv/bin/python3 -m sphinx" SPHINXOPTS="-nW -q -b linkcheck"
    - os: linux
      language: c
      compiler: clang
      env:
        - TESTING=coverage
      before_script:
        - ./configure
        - make -s -j4
        - ./python -m venv venv
        - ./venv/bin/python -m pip install -U coverage 
        - export COVERAGE_PROCESS_START=$(pwd)/Misc/coveragerc
        - echo "import coverage; coverage.process_startup()" > "$(./venv/bin/python -c "import sysconfig; print(sysconfig.get_path('platlib'))")"/sitecustomize.py
      script:
        # Skip tests that re-run the entire test suite.
        - ./venv/bin/python -m coverage run --pylib -m test -uall -j4 -x test_multiprocessing_fork -x test_multiprocessing_forkserver -x test_multiprocessing_spawn
      after_script:
        - rm "$(./venv/bin/python -c "import sysconfig; print(sysconfig.get_path('platlib'))")"/sitecustomize.py
        # Make the `coverage` command available to Codecov w/ a version of Python that can parse all source files.
        - source ./venv/bin/activate 
        - bash <(curl -s https://codecov.io/bash)

# Travis provides only 2 cores, so don't overdue the parallelism and waste memory.
before_script:
  - ./configure --with-pydebug
  - make -j4

script:
  # `-r -w` implicitly provided through `make test`.
  - make test TESTOPTS="-uall -j4"

notifications:
  email: false
